const dynamicChunks = {
 ['21.js']: () => import('../app/21.mjs').then(function (n) { return n._; }),
 ['components/auth.js']: () => import('../app/components/auth.mjs').then(function (n) { return n.a; }),
 ['components/clients-guests.js']: () => import('../app/components/clients-guests.mjs').then(function (n) { return n.c; }),
 ['components/clients-registeds.js']: () => import('../app/components/clients-registeds.mjs').then(function (n) { return n.c; }),
 ['components/coupons-create-coupons.js']: () => import('../app/components/coupons-create-coupons.mjs').then(function (n) { return n.c; }),
 ['components/coupons-table.js']: () => import('../app/components/coupons-table.mjs').then(function (n) { return n.c; }),
 ['components/dashboard-analytics-google.js']: () => import('../app/components/dashboard-analytics-google.mjs').then(function (n) { return n.d; }),
 ['components/dashboard-donuts-products.js']: () => import('../app/components/dashboard-donuts-products.mjs').then(function (n) { return n.d; }),
 ['components/dashboard-graphic-months.js']: () => import('../app/components/dashboard-graphic-months.mjs').then(function (n) { return n.d; }),
 ['components/header-with-topbar.js']: () => import('../app/components/header-with-topbar.mjs').then(function (n) { return n.h; }),
 ['components/headers-nav-top.js']: () => import('../app/components/headers-nav-top.mjs').then(function (n) { return n.h; }),
 ['components/headers-results.js']: () => import('../app/components/headers-results.mjs').then(function (n) { return n.h; }),
 ['components/headers-search.js']: () => import('../app/components/headers-search.mjs').then(function (n) { return n.h; }),
 ['components/headers-side-nav.js']: () => import('../app/components/headers-side-nav.mjs').then(function (n) { return n.h; }),
 ['components/invoices-error-modal.js']: () => import('../app/components/invoices-error-modal.mjs').then(function (n) { return n.i; }),
 ['components/invoices-invoice-viewer.js']: () => import('../app/components/invoices-invoice-viewer.mjs').then(function (n) { return n.i; }),
 ['components/invoices-new-invoice.js']: () => import('../app/components/invoices-new-invoice.mjs').then(function (n) { return n.i; }),
 ['components/invoices-success-invoice-modal.js']: () => import('../app/components/invoices-success-invoice-modal.mjs').then(function (n) { return n.i; }),
 ['components/invoices-table.js']: () => import('../app/components/invoices-table.mjs').then(function (n) { return n.i; }),
 ['components/loaders-big-loader.js']: () => import('../app/components/loaders-big-loader.mjs').then(function (n) { return n.l; }),
 ['components/loaders-small-loading.js']: () => import('../app/components/loaders-small-loading.mjs').then(function (n) { return n.l; }),
 ['components/login.js']: () => import('../app/components/login.mjs').then(function (n) { return n.l; }),
 ['components/mobile-bar.js']: () => import('../app/components/mobile-bar.mjs').then(function (n) { return n.m; }),
 ['components/my-account-container.js']: () => import('../app/components/my-account-container.mjs').then(function (n) { return n.m; }),
 ['components/nav-bottom.js']: () => import('../app/components/nav-bottom.mjs').then(function (n) { return n.n; }),
 ['components/navigation.js']: () => import('../app/components/navigation.mjs').then(function (n) { return n.n; }),
 ['components/off-canvas-mobile-menu.js']: () => import('../app/components/off-canvas-mobile-menu.mjs').then(function (n) { return n.o; }),
 ['components/orders-com.js']: () => import('../app/components/orders-com.mjs').then(function (n) { return n.o; }),
 ['components/orders-edit-order.js']: () => import('../app/components/orders-edit-order.mjs').then(function (n) { return n.o; }),
 ['components/orders-history.js']: () => import('../app/components/orders-history.mjs').then(function (n) { return n.o; }),
 ['components/orders-modal-track.js']: () => import('../app/components/orders-modal-track.mjs').then(function (n) { return n.o; }),
 ['components/orders-note.js']: () => import('../app/components/orders-note.mjs').then(function (n) { return n.o; }),
 ['components/orders.js']: () => import('../app/components/orders.mjs').then(function (n) { return n.o; }),
 ['components/product-create-product.js']: () => import('../app/components/product-create-product.mjs').then(function (n) { return n.p; }),
 ['components/product-details-description-review.js']: () => import('../app/components/product-details-description-review.mjs').then(function (n) { return n.p; }),
 ['components/product-details-wrapper.js']: () => import('../app/components/product-details-wrapper.mjs').then(function (n) { return n.p; }),
 ['components/product-edit-product.js']: () => import('../app/components/product-edit-product.mjs').then(function (n) { return n.p; }),
 ['components/product-grid-item-two.js']: () => import('../app/components/product-grid-item-two.mjs').then(function (n) { return n.p; }),
 ['components/product-grid-item.js']: () => import('../app/components/product-grid-item.mjs').then(function (n) { return n.p; }),
 ['components/product-grid-style-three.js']: () => import('../app/components/product-grid-style-three.mjs').then(function (n) { return n.p; }),
 ['components/product-products-table.js']: () => import('../app/components/product-products-table.mjs').then(function (n) { return n.p; }),
 ['components/product-wrapper-cosmetics.js']: () => import('../app/components/product-wrapper-cosmetics.mjs').then(function (n) { return n.p; }),
 ['components/profile-new-guest.js']: () => import('../app/components/profile-new-guest.mjs').then(function (n) { return n.p; }),
 ['components/profile-new-profile.js']: () => import('../app/components/profile-new-profile.mjs').then(function (n) { return n.p; }),
 ['components/register.js']: () => import('../app/components/register.mjs').then(function (n) { return n.r; }),
 ['components/responsive-mobile-menu.js']: () => import('../app/components/responsive-mobile-menu.mjs').then(function (n) { return n.r; }),
 ['components/reviews-new-review.js']: () => import('../app/components/reviews-new-review.mjs').then(function (n) { return n.r; }),
 ['components/reviews-review-table.js']: () => import('../app/components/reviews-review-table.mjs').then(function (n) { return n.r; }),
 ['components/search.js']: () => import('../app/components/search.mjs').then(function (n) { return n.s; }),
 ['components/the-footer.js']: () => import('../app/components/the-footer.mjs').then(function (n) { return n.t; }),
 ['components/the-header.js']: () => import('../app/components/the-header.mjs').then(function (n) { return n.t; }),
 ['pages/clients.js']: () => import('../app/pages/clients.mjs').then(function (n) { return n.c; }),
 ['pages/coupons.js']: () => import('../app/pages/coupons.mjs').then(function (n) { return n.c; }),
 ['pages/guests.js']: () => import('../app/pages/guests.mjs').then(function (n) { return n.g; }),
 ['pages/index.js']: () => import('../app/pages/index.mjs').then(function (n) { return n.i; }),
 ['pages/invoices.js']: () => import('../app/pages/invoices.mjs').then(function (n) { return n.i; }),
 ['pages/login.js']: () => import('../app/pages/login.mjs').then(function (n) { return n.l; }),
 ['pages/my-account.js']: () => import('../app/pages/my-account.mjs').then(function (n) { return n.m; }),
 ['pages/orders-history.js']: () => import('../app/pages/orders-history.mjs').then(function (n) { return n.o; }),
 ['pages/orders.js']: () => import('../app/pages/orders.mjs').then(function (n) { return n.o; }),
 ['pages/products.js']: () => import('../app/pages/products.mjs').then(function (n) { return n.p; }),
 ['pages/reviews.js']: () => import('../app/pages/reviews.mjs').then(function (n) { return n.r; }),
 ['pages/settings.js']: () => import('../app/pages/settings.mjs').then(function (n) { return n.s; }),
 ['pages/order-edit/_id.js']: () => import('../app/pages/order-edit/_id.mjs').then(function (n) { return n._; }),
 ['pages/orders-view/_id.js']: () => import('../app/pages/orders-view/_id.mjs').then(function (n) { return n._; }),
 ['pages/product/_slug.js']: () => import('../app/pages/product/_slug.mjs').then(function (n) { return n._; })
};

function dynamicRequire(id) {
  return dynamicChunks[id]();
}

export { dynamicRequire as default };
//# sourceMappingURL=_dynamic-require.mjs.map
