// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Auth': typeof import("../components/Auth.vue")['default'],
    'HeaderWithTopbar': typeof import("../components/HeaderWithTopbar.vue")['default'],
    'Login': typeof import("../components/Login.vue")['default'],
    'MobileBar': typeof import("../components/MobileBar.vue")['default'],
    'MyAccountContainer': typeof import("../components/MyAccountContainer.vue")['default'],
    'NavBottom': typeof import("../components/NavBottom.vue")['default'],
    'Navigation': typeof import("../components/Navigation.vue")['default'],
    'OffCanvasMobileMenu': typeof import("../components/OffCanvasMobileMenu.vue")['default'],
    'ProductDetailsDescriptionReview': typeof import("../components/ProductDetailsDescriptionReview.vue")['default'],
    'Register': typeof import("../components/Register.vue")['default'],
    'ResponsiveMobileMenu': typeof import("../components/ResponsiveMobileMenu.vue")['default'],
    'Search': typeof import("../components/Search.vue")['default'],
    'TheFooter': typeof import("../components/TheFooter.vue")['default'],
    'TheHeader': typeof import("../components/TheHeader.vue")['default'],
    'CouponsTable': typeof import("../components/coupons/CouponsTable.vue")['default'],
    'CouponsCreateCoupons': typeof import("../components/coupons/CreateCoupons.vue")['default'],
    'ClientsGuests': typeof import("../components/clients/Guests.vue")['default'],
    'ClientsRegisteds': typeof import("../components/clients/Registeds.vue")['default'],
    'DashboardAnalyticsGoogle': typeof import("../components/dashboard/AnalyticsGoogle.vue")['default'],
    'DashboardDonutsProducts': typeof import("../components/dashboard/DonutsProducts.vue")['default'],
    'DashboardGraphicMonths': typeof import("../components/dashboard/GraphicMonths.vue")['default'],
    'GiftsCreateGift': typeof import("../components/gifts/CreateGift.vue")['default'],
    'GiftsTable': typeof import("../components/gifts/GiftsTable.vue")['default'],
    'HeadersNavTop': typeof import("../components/headers/NavTop.vue")['default'],
    'HeadersResults': typeof import("../components/headers/Results.vue")['default'],
    'HeadersSearch': typeof import("../components/headers/Search.vue")['default'],
    'HeadersSideNav': typeof import("../components/headers/SideNav.vue")['default'],
    'InvoicesErrorModal': typeof import("../components/invoices/ErrorModal.vue")['default'],
    'InvoicesInvoiceViewer': typeof import("../components/invoices/InvoiceViewer.vue")['default'],
    'InvoicesTable': typeof import("../components/invoices/InvoicesTable.vue")['default'],
    'InvoicesNewInvoice': typeof import("../components/invoices/NewInvoice.vue")['default'],
    'InvoicesSuccessInvoiceModal': typeof import("../components/invoices/SuccessInvoiceModal.vue")['default'],
    'DiscountsCreateDiscount': typeof import("../components/discounts/CreateDiscount.vue")['default'],
    'DiscountsTable': typeof import("../components/discounts/DiscountsTable.vue")['default'],
    'LoadersBigLoader': typeof import("../components/loaders/BigLoader.vue")['default'],
    'LoadersSmallLoading': typeof import("../components/loaders/SmallLoading.vue")['default'],
    'OrdersEditOrder': typeof import("../components/orders/EditOrder.vue")['default'],
    'OrdersModalTrack': typeof import("../components/orders/ModalTrack.vue")['default'],
    'OrdersNote': typeof import("../components/orders/Note.vue")['default'],
    'Orders': typeof import("../components/orders/Orders.vue")['default'],
    'OrdersCom': typeof import("../components/orders/OrdersCom.vue")['default'],
    'OrdersHistory': typeof import("../components/orders/OrdersHistory.vue")['default'],
    'ProductCreateProduct': typeof import("../components/product/CreateProduct.vue")['default'],
    'ProductEditProduct': typeof import("../components/product/EditProduct.vue")['default'],
    'ProductDetailsWrapper': typeof import("../components/product/ProductDetailsWrapper.vue")['default'],
    'ProductGridItem': typeof import("../components/product/ProductGridItem.vue")['default'],
    'ProductGridItemTwo': typeof import("../components/product/ProductGridItemTwo.vue")['default'],
    'ProductGridStyleThree': typeof import("../components/product/ProductGridStyleThree.vue")['default'],
    'ProductWrapperCosmetics': typeof import("../components/product/ProductWrapperCosmetics.vue")['default'],
    'ProductProductsTable': typeof import("../components/product/ProductsTable.vue")['default'],
    'ProfileNewGuest': typeof import("../components/profile/NewGuest.vue")['default'],
    'ProfileNewProfile': typeof import("../components/profile/NewProfile.vue")['default'],
    'ReviewsNewReview': typeof import("../components/reviews/NewReview.vue")['default'],
    'ReviewsReviewTable': typeof import("../components/reviews/ReviewTable.vue")['default'],
    'VariationsCreateVariation': typeof import("../components/variations/CreateVariation.vue")['default'],
    'VariationsTable': typeof import("../components/variations/VariationsTable.vue")['default']
    'LazyAuth': typeof import("../components/Auth.vue")['default'],
    'LazyHeaderWithTopbar': typeof import("../components/HeaderWithTopbar.vue")['default'],
    'LazyLogin': typeof import("../components/Login.vue")['default'],
    'LazyMobileBar': typeof import("../components/MobileBar.vue")['default'],
    'LazyMyAccountContainer': typeof import("../components/MyAccountContainer.vue")['default'],
    'LazyNavBottom': typeof import("../components/NavBottom.vue")['default'],
    'LazyNavigation': typeof import("../components/Navigation.vue")['default'],
    'LazyOffCanvasMobileMenu': typeof import("../components/OffCanvasMobileMenu.vue")['default'],
    'LazyProductDetailsDescriptionReview': typeof import("../components/ProductDetailsDescriptionReview.vue")['default'],
    'LazyRegister': typeof import("../components/Register.vue")['default'],
    'LazyResponsiveMobileMenu': typeof import("../components/ResponsiveMobileMenu.vue")['default'],
    'LazySearch': typeof import("../components/Search.vue")['default'],
    'LazyTheFooter': typeof import("../components/TheFooter.vue")['default'],
    'LazyTheHeader': typeof import("../components/TheHeader.vue")['default'],
    'LazyCouponsTable': typeof import("../components/coupons/CouponsTable.vue")['default'],
    'LazyCouponsCreateCoupons': typeof import("../components/coupons/CreateCoupons.vue")['default'],
    'LazyClientsGuests': typeof import("../components/clients/Guests.vue")['default'],
    'LazyClientsRegisteds': typeof import("../components/clients/Registeds.vue")['default'],
    'LazyDashboardAnalyticsGoogle': typeof import("../components/dashboard/AnalyticsGoogle.vue")['default'],
    'LazyDashboardDonutsProducts': typeof import("../components/dashboard/DonutsProducts.vue")['default'],
    'LazyDashboardGraphicMonths': typeof import("../components/dashboard/GraphicMonths.vue")['default'],
    'LazyGiftsCreateGift': typeof import("../components/gifts/CreateGift.vue")['default'],
    'LazyGiftsTable': typeof import("../components/gifts/GiftsTable.vue")['default'],
    'LazyHeadersNavTop': typeof import("../components/headers/NavTop.vue")['default'],
    'LazyHeadersResults': typeof import("../components/headers/Results.vue")['default'],
    'LazyHeadersSearch': typeof import("../components/headers/Search.vue")['default'],
    'LazyHeadersSideNav': typeof import("../components/headers/SideNav.vue")['default'],
    'LazyInvoicesErrorModal': typeof import("../components/invoices/ErrorModal.vue")['default'],
    'LazyInvoicesInvoiceViewer': typeof import("../components/invoices/InvoiceViewer.vue")['default'],
    'LazyInvoicesTable': typeof import("../components/invoices/InvoicesTable.vue")['default'],
    'LazyInvoicesNewInvoice': typeof import("../components/invoices/NewInvoice.vue")['default'],
    'LazyInvoicesSuccessInvoiceModal': typeof import("../components/invoices/SuccessInvoiceModal.vue")['default'],
    'LazyDiscountsCreateDiscount': typeof import("../components/discounts/CreateDiscount.vue")['default'],
    'LazyDiscountsTable': typeof import("../components/discounts/DiscountsTable.vue")['default'],
    'LazyLoadersBigLoader': typeof import("../components/loaders/BigLoader.vue")['default'],
    'LazyLoadersSmallLoading': typeof import("../components/loaders/SmallLoading.vue")['default'],
    'LazyOrdersEditOrder': typeof import("../components/orders/EditOrder.vue")['default'],
    'LazyOrdersModalTrack': typeof import("../components/orders/ModalTrack.vue")['default'],
    'LazyOrdersNote': typeof import("../components/orders/Note.vue")['default'],
    'LazyOrders': typeof import("../components/orders/Orders.vue")['default'],
    'LazyOrdersCom': typeof import("../components/orders/OrdersCom.vue")['default'],
    'LazyOrdersHistory': typeof import("../components/orders/OrdersHistory.vue")['default'],
    'LazyProductCreateProduct': typeof import("../components/product/CreateProduct.vue")['default'],
    'LazyProductEditProduct': typeof import("../components/product/EditProduct.vue")['default'],
    'LazyProductDetailsWrapper': typeof import("../components/product/ProductDetailsWrapper.vue")['default'],
    'LazyProductGridItem': typeof import("../components/product/ProductGridItem.vue")['default'],
    'LazyProductGridItemTwo': typeof import("../components/product/ProductGridItemTwo.vue")['default'],
    'LazyProductGridStyleThree': typeof import("../components/product/ProductGridStyleThree.vue")['default'],
    'LazyProductWrapperCosmetics': typeof import("../components/product/ProductWrapperCosmetics.vue")['default'],
    'LazyProductProductsTable': typeof import("../components/product/ProductsTable.vue")['default'],
    'LazyProfileNewGuest': typeof import("../components/profile/NewGuest.vue")['default'],
    'LazyProfileNewProfile': typeof import("../components/profile/NewProfile.vue")['default'],
    'LazyReviewsNewReview': typeof import("../components/reviews/NewReview.vue")['default'],
    'LazyReviewsReviewTable': typeof import("../components/reviews/ReviewTable.vue")['default'],
    'LazyVariationsCreateVariation': typeof import("../components/variations/CreateVariation.vue")['default'],
    'LazyVariationsTable': typeof import("../components/variations/VariationsTable.vue")['default']
  }
}
export const Auth: typeof import("../components/Auth.vue")['default']
export const HeaderWithTopbar: typeof import("../components/HeaderWithTopbar.vue")['default']
export const Login: typeof import("../components/Login.vue")['default']
export const MobileBar: typeof import("../components/MobileBar.vue")['default']
export const MyAccountContainer: typeof import("../components/MyAccountContainer.vue")['default']
export const NavBottom: typeof import("../components/NavBottom.vue")['default']
export const Navigation: typeof import("../components/Navigation.vue")['default']
export const OffCanvasMobileMenu: typeof import("../components/OffCanvasMobileMenu.vue")['default']
export const ProductDetailsDescriptionReview: typeof import("../components/ProductDetailsDescriptionReview.vue")['default']
export const Register: typeof import("../components/Register.vue")['default']
export const ResponsiveMobileMenu: typeof import("../components/ResponsiveMobileMenu.vue")['default']
export const Search: typeof import("../components/Search.vue")['default']
export const TheFooter: typeof import("../components/TheFooter.vue")['default']
export const TheHeader: typeof import("../components/TheHeader.vue")['default']
export const CouponsTable: typeof import("../components/coupons/CouponsTable.vue")['default']
export const CouponsCreateCoupons: typeof import("../components/coupons/CreateCoupons.vue")['default']
export const ClientsGuests: typeof import("../components/clients/Guests.vue")['default']
export const ClientsRegisteds: typeof import("../components/clients/Registeds.vue")['default']
export const DashboardAnalyticsGoogle: typeof import("../components/dashboard/AnalyticsGoogle.vue")['default']
export const DashboardDonutsProducts: typeof import("../components/dashboard/DonutsProducts.vue")['default']
export const DashboardGraphicMonths: typeof import("../components/dashboard/GraphicMonths.vue")['default']
export const GiftsCreateGift: typeof import("../components/gifts/CreateGift.vue")['default']
export const GiftsTable: typeof import("../components/gifts/GiftsTable.vue")['default']
export const HeadersNavTop: typeof import("../components/headers/NavTop.vue")['default']
export const HeadersResults: typeof import("../components/headers/Results.vue")['default']
export const HeadersSearch: typeof import("../components/headers/Search.vue")['default']
export const HeadersSideNav: typeof import("../components/headers/SideNav.vue")['default']
export const InvoicesErrorModal: typeof import("../components/invoices/ErrorModal.vue")['default']
export const InvoicesInvoiceViewer: typeof import("../components/invoices/InvoiceViewer.vue")['default']
export const InvoicesTable: typeof import("../components/invoices/InvoicesTable.vue")['default']
export const InvoicesNewInvoice: typeof import("../components/invoices/NewInvoice.vue")['default']
export const InvoicesSuccessInvoiceModal: typeof import("../components/invoices/SuccessInvoiceModal.vue")['default']
export const DiscountsCreateDiscount: typeof import("../components/discounts/CreateDiscount.vue")['default']
export const DiscountsTable: typeof import("../components/discounts/DiscountsTable.vue")['default']
export const LoadersBigLoader: typeof import("../components/loaders/BigLoader.vue")['default']
export const LoadersSmallLoading: typeof import("../components/loaders/SmallLoading.vue")['default']
export const OrdersEditOrder: typeof import("../components/orders/EditOrder.vue")['default']
export const OrdersModalTrack: typeof import("../components/orders/ModalTrack.vue")['default']
export const OrdersNote: typeof import("../components/orders/Note.vue")['default']
export const Orders: typeof import("../components/orders/Orders.vue")['default']
export const OrdersCom: typeof import("../components/orders/OrdersCom.vue")['default']
export const OrdersHistory: typeof import("../components/orders/OrdersHistory.vue")['default']
export const ProductCreateProduct: typeof import("../components/product/CreateProduct.vue")['default']
export const ProductEditProduct: typeof import("../components/product/EditProduct.vue")['default']
export const ProductDetailsWrapper: typeof import("../components/product/ProductDetailsWrapper.vue")['default']
export const ProductGridItem: typeof import("../components/product/ProductGridItem.vue")['default']
export const ProductGridItemTwo: typeof import("../components/product/ProductGridItemTwo.vue")['default']
export const ProductGridStyleThree: typeof import("../components/product/ProductGridStyleThree.vue")['default']
export const ProductWrapperCosmetics: typeof import("../components/product/ProductWrapperCosmetics.vue")['default']
export const ProductProductsTable: typeof import("../components/product/ProductsTable.vue")['default']
export const ProfileNewGuest: typeof import("../components/profile/NewGuest.vue")['default']
export const ProfileNewProfile: typeof import("../components/profile/NewProfile.vue")['default']
export const ReviewsNewReview: typeof import("../components/reviews/NewReview.vue")['default']
export const ReviewsReviewTable: typeof import("../components/reviews/ReviewTable.vue")['default']
export const VariationsCreateVariation: typeof import("../components/variations/CreateVariation.vue")['default']
export const VariationsTable: typeof import("../components/variations/VariationsTable.vue")['default']
export const LazyAuth: typeof import("../components/Auth.vue")['default']
export const LazyHeaderWithTopbar: typeof import("../components/HeaderWithTopbar.vue")['default']
export const LazyLogin: typeof import("../components/Login.vue")['default']
export const LazyMobileBar: typeof import("../components/MobileBar.vue")['default']
export const LazyMyAccountContainer: typeof import("../components/MyAccountContainer.vue")['default']
export const LazyNavBottom: typeof import("../components/NavBottom.vue")['default']
export const LazyNavigation: typeof import("../components/Navigation.vue")['default']
export const LazyOffCanvasMobileMenu: typeof import("../components/OffCanvasMobileMenu.vue")['default']
export const LazyProductDetailsDescriptionReview: typeof import("../components/ProductDetailsDescriptionReview.vue")['default']
export const LazyRegister: typeof import("../components/Register.vue")['default']
export const LazyResponsiveMobileMenu: typeof import("../components/ResponsiveMobileMenu.vue")['default']
export const LazySearch: typeof import("../components/Search.vue")['default']
export const LazyTheFooter: typeof import("../components/TheFooter.vue")['default']
export const LazyTheHeader: typeof import("../components/TheHeader.vue")['default']
export const LazyCouponsTable: typeof import("../components/coupons/CouponsTable.vue")['default']
export const LazyCouponsCreateCoupons: typeof import("../components/coupons/CreateCoupons.vue")['default']
export const LazyClientsGuests: typeof import("../components/clients/Guests.vue")['default']
export const LazyClientsRegisteds: typeof import("../components/clients/Registeds.vue")['default']
export const LazyDashboardAnalyticsGoogle: typeof import("../components/dashboard/AnalyticsGoogle.vue")['default']
export const LazyDashboardDonutsProducts: typeof import("../components/dashboard/DonutsProducts.vue")['default']
export const LazyDashboardGraphicMonths: typeof import("../components/dashboard/GraphicMonths.vue")['default']
export const LazyGiftsCreateGift: typeof import("../components/gifts/CreateGift.vue")['default']
export const LazyGiftsTable: typeof import("../components/gifts/GiftsTable.vue")['default']
export const LazyHeadersNavTop: typeof import("../components/headers/NavTop.vue")['default']
export const LazyHeadersResults: typeof import("../components/headers/Results.vue")['default']
export const LazyHeadersSearch: typeof import("../components/headers/Search.vue")['default']
export const LazyHeadersSideNav: typeof import("../components/headers/SideNav.vue")['default']
export const LazyInvoicesErrorModal: typeof import("../components/invoices/ErrorModal.vue")['default']
export const LazyInvoicesInvoiceViewer: typeof import("../components/invoices/InvoiceViewer.vue")['default']
export const LazyInvoicesTable: typeof import("../components/invoices/InvoicesTable.vue")['default']
export const LazyInvoicesNewInvoice: typeof import("../components/invoices/NewInvoice.vue")['default']
export const LazyInvoicesSuccessInvoiceModal: typeof import("../components/invoices/SuccessInvoiceModal.vue")['default']
export const LazyDiscountsCreateDiscount: typeof import("../components/discounts/CreateDiscount.vue")['default']
export const LazyDiscountsTable: typeof import("../components/discounts/DiscountsTable.vue")['default']
export const LazyLoadersBigLoader: typeof import("../components/loaders/BigLoader.vue")['default']
export const LazyLoadersSmallLoading: typeof import("../components/loaders/SmallLoading.vue")['default']
export const LazyOrdersEditOrder: typeof import("../components/orders/EditOrder.vue")['default']
export const LazyOrdersModalTrack: typeof import("../components/orders/ModalTrack.vue")['default']
export const LazyOrdersNote: typeof import("../components/orders/Note.vue")['default']
export const LazyOrders: typeof import("../components/orders/Orders.vue")['default']
export const LazyOrdersCom: typeof import("../components/orders/OrdersCom.vue")['default']
export const LazyOrdersHistory: typeof import("../components/orders/OrdersHistory.vue")['default']
export const LazyProductCreateProduct: typeof import("../components/product/CreateProduct.vue")['default']
export const LazyProductEditProduct: typeof import("../components/product/EditProduct.vue")['default']
export const LazyProductDetailsWrapper: typeof import("../components/product/ProductDetailsWrapper.vue")['default']
export const LazyProductGridItem: typeof import("../components/product/ProductGridItem.vue")['default']
export const LazyProductGridItemTwo: typeof import("../components/product/ProductGridItemTwo.vue")['default']
export const LazyProductGridStyleThree: typeof import("../components/product/ProductGridStyleThree.vue")['default']
export const LazyProductWrapperCosmetics: typeof import("../components/product/ProductWrapperCosmetics.vue")['default']
export const LazyProductProductsTable: typeof import("../components/product/ProductsTable.vue")['default']
export const LazyProfileNewGuest: typeof import("../components/profile/NewGuest.vue")['default']
export const LazyProfileNewProfile: typeof import("../components/profile/NewProfile.vue")['default']
export const LazyReviewsNewReview: typeof import("../components/reviews/NewReview.vue")['default']
export const LazyReviewsReviewTable: typeof import("../components/reviews/ReviewTable.vue")['default']
export const LazyVariationsCreateVariation: typeof import("../components/variations/CreateVariation.vue")['default']
export const LazyVariationsTable: typeof import("../components/variations/VariationsTable.vue")['default']
export const componentNames: string[]
